apiVersion: v2
name: ollama
description: A Helm chart for Ollama
type: application
version: 1.0.0
appVersion: "latest"

service:
  type: ClusterIP
  port: 11434

deployment:
  replicas: 1
  image: ollama/ollama:latest
