apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: PASSWORD
          value: {{ .Values.deployment.env.PASSWORD }}
