apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: code-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app: code-server
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
