# Code-Server Service Configuration
service:
  name: code-server
  type: ClusterIP
  port: 8080

# Deployment Configuration
replicaCount: 1

image:
  repository: codercom/code-server
  tag: latest
  pullPolicy: IfNotPresent

# Resource Limits and Requests
resources:
  limits:
    cpu: "2000m"
    memory: "2048Mi"
  requests:
    cpu: "1000m"
    memory: "1024Mi"

# Persistent Storage Configuration
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  storageClassName: "standard"

# Ingress Configuration
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: localhost
  path: /code-server

# Environment Variables
env:
  - name: PASSWORD
    value: "codeadmin"

# Volume Mounts
volumeMounts:
  - name: code-server-data
    mountPath: /home/coder/project
