apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: jupyterhub
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jupyterhub
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
