apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: flowise
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flowise
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
