# ChromaDB Service Configuration
service:
  name: chromadb
  type: ClusterIP
  port: 8000

# Deployment Configuration
replicaCount: 1

image:
  repository: ghcr.io/chroma-core/chroma
  tag: latest
  pullPolicy: IfNotPresent

# Resource Limits and Requests
resources:
  limits:
    cpu: "1000m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"

# Persistent Storage Configuration
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  storageClassName: "standard"

# Ingress Configuration
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: localhost
  path: /chromadb

# Environment Variables
env:
  - name: CHROMA_SERVER_HOST
    value: "0.0.0.0"
  - name: CHROMA_SERVER_PORT
    value: "8000"
  - name: CHROMA_DB_PATH
    value: "/data"

# Volume Mounts
volumeMounts:
  - name: chroma-data
    mountPath: /data

# Node Selector, Tolerations, and Affinity (optional)
nodeSelector: {}
tolerations: []
affinity: {}

# Extra Configuration (Optional for Debugging or Logs)
extraArgs: []
