# Langflow Service Configuration
service:
  name: langflow
  type: ClusterIP
  port: 7860

# Deployment Configuration
replicaCount: 1

image:
  repository: ghcr.io/langflow-ai/langflow
  tag: latest
  pullPolicy: IfNotPresent

# Resource Limits and Requests
resources:
  limits:
    cpu: "2000m"
    memory: "2048Mi"
  requests:
    cpu: "1000m"
    memory: "1024Mi"

# Persistent Storage Configuration
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  storageClassName: "standard"

# Ingress Configuration
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: localhost
  path: /langflow

# Environment Variables
env:
  - name: PORT
    value: "7860"

# Volume Mounts
volumeMounts:
  - name: langflow-data
    mountPath: /app/langflow-data
