# Flowise Service Configuration
service:
  name: flowise
  type: ClusterIP
  port: 3000

# Deployment Configuration
replicaCount: 1

image:
  repository: flowiseai/flowise
  tag: latest
  pullPolicy: IfNotPresent

# Resource Limits and Requests
resources:
  limits:
    cpu: "1000m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"

# Persistent Storage Configuration
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  storageClassName: "standard"

# Ingress Configuration
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: localhost
  path: /flowise

# Environment Variables
env:
  - name: PORT
    value: "3000"
  - name: FLOWISE_STORAGE_PATH
    value: "/data"

# Volume Mounts
volumeMounts:
  - name: flowise-data
    mountPath: /data
